application: henrydbissonnette
version: 1-0-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: /static/images/favicon.ico
  upload: /static/images/favicon.ico
  
- url: /static/
  static_dir: static/
  
- url: /static/images/
  static_dir: static/images/

- url: .*
  script: main.app

libraries:
- name: django
  version: "1.2"
- name: webapp2
  version: "2.5.1"
